import type { DemoState } from "./demo-schema"

// allow: SIZE_OK — Korean fixture seed data is an indivisible data table.
export const DEMO_USER_ID = "profile-yuna"
export const DEMO_ADMIN_ID = "profile-admin"

export const demoFixtureState: DemoState = {
  viewerId: null,
  profiles: [
    {
      id: DEMO_USER_ID,
      handle: "yunapath",
      name: "윤아",
      bio: "비 오는 날의 카페와 오래 걷는 골목을 모읍니다.",
      avatarTone: "coral",
      role: "user",
      createdAt: "2026-05-01T09:00:00.000Z",
    },
    {
      id: "profile-minseo",
      handle: "minseo.local",
      name: "민서",
      bio: "혼자 머물기 좋은 공간 기록자.",
      avatarTone: "mint",
      role: "user",
      createdAt: "2026-05-03T09:00:00.000Z",
    },
    {
      id: "profile-jun",
      handle: "junwalks",
      name: "준",
      bio: "산책과 작은 전시를 따라 걷습니다.",
      avatarTone: "forest",
      role: "user",
      createdAt: "2026-05-05T09:00:00.000Z",
    },
    {
      id: DEMO_ADMIN_ID,
      handle: "loca.editor",
      name: "LOCA 에디터",
      bio: "이번 주의 장소 흐름을 큐레이션합니다.",
      avatarTone: "blue",
      role: "admin",
      createdAt: "2026-04-01T09:00:00.000Z",
    },
  ],
  places: [
    {
      id: "place-brewers",
      provider: "demo",
      providerPlaceId: "demo-brewers",
      name: "브루어스 커피",
      normalizedName: "브루어스 커피",
      address: "서울 마포구 와우산로 17길 22",
      region: "망원",
      coordinates: { latitude: 37.5557, longitude: 126.9065 },
      category: "카페",
      representativeTone: "coral",
      verificationStatus: "verified",
      createdBy: null,
      createdAt: "2026-05-01T09:00:00.000Z",
    },
    {
      id: "place-moon-library",
      provider: "demo",
      providerPlaceId: "demo-moon-library",
      name: "달빛책방",
      normalizedName: "달빛책방",
      address: "서울 종로구 자하문로 31",
      region: "서촌",
      coordinates: { latitude: 37.5795, longitude: 126.9708 },
      category: "서점",
      representativeTone: "violet",
      verificationStatus: "verified",
      createdBy: null,
      createdAt: "2026-05-01T09:00:00.000Z",
    },
    {
      id: "place-rain-yard",
      provider: "demo",
      providerPlaceId: "demo-rain-yard",
      name: "비마당",
      normalizedName: "비마당",
      address: "서울 성동구 서울숲2길 8",
      region: "성수",
      coordinates: { latitude: 37.5444, longitude: 127.0428 },
      category: "복합문화공간",
      representativeTone: "mint",
      verificationStatus: "verified",
      createdBy: null,
      createdAt: "2026-05-02T09:00:00.000Z",
    },
    {
      id: "place-archive-93",
      provider: "demo",
      providerPlaceId: "demo-archive-93",
      name: "아카이브 93",
      normalizedName: "아카이브 93",
      address: "서울 용산구 회나무로 9",
      region: "해방촌",
      coordinates: { latitude: 37.5416, longitude: 126.9874 },
      category: "갤러리",
      representativeTone: "amber",
      verificationStatus: "verified",
      createdBy: null,
      createdAt: "2026-05-02T09:00:00.000Z",
    },
    {
      id: "place-blue-stairs",
      provider: "demo",
      providerPlaceId: "demo-blue-stairs",
      name: "푸른계단",
      normalizedName: "푸른계단",
      address: "서울 중구 퇴계로 20길 14",
      region: "남산",
      coordinates: { latitude: 37.5583, longitude: 126.9876 },
      category: "산책로",
      representativeTone: "blue",
      verificationStatus: "verified",
      createdBy: null,
      createdAt: "2026-05-03T09:00:00.000Z",
    },
  ],
  media: [
    {
      id: "media-exp-1",
      experienceId: "exp-brewers-rain",
      mediaType: "image",
      storagePath: "demo/brewers-rain.jpg",
      posterPath: null,
      sortOrder: 0,
      mimeType: "image/jpeg",
      sizeBytes: 640000,
      durationSeconds: null,
      tone: "coral",
    },
    {
      id: "media-exp-2",
      experienceId: "exp-moon-silent",
      mediaType: "image",
      storagePath: "demo/moon-silent.jpg",
      posterPath: null,
      sortOrder: 0,
      mimeType: "image/jpeg",
      sizeBytes: 588000,
      durationSeconds: null,
      tone: "violet",
    },
    {
      id: "media-exp-3",
      experienceId: "exp-rain-yard",
      mediaType: "video",
      storagePath: "demo/rain-yard.webm",
      posterPath: "demo/rain-yard-poster.jpg",
      sortOrder: 0,
      mimeType: "video/webm",
      sizeBytes: 2200000,
      durationSeconds: 12,
      tone: "mint",
    },
    {
      id: "media-exp-4",
      experienceId: "exp-archive-quiet",
      mediaType: "image",
      storagePath: "demo/archive-quiet.jpg",
      posterPath: null,
      sortOrder: 0,
      mimeType: "image/jpeg",
      sizeBytes: 490000,
      durationSeconds: null,
      tone: "amber",
    },
  ],
  experiences: [
    {
      id: "exp-brewers-rain",
      userId: "profile-minseo",
      placeId: "place-brewers",
      caption: "비가 그친 뒤 창가 자리가 제일 먼저 따뜻해졌다.",
      tags: ["비 오는 날", "혼자 있고 싶은 날"],
      visitedAt: "2026-06-10T07:30:00.000Z",
      showVisitedAt: true,
      visibility: "public",
      status: "active",
      shareToken: "share-exp-brewers-rain",
      createdAt: "2026-06-10T09:00:00.000Z",
    },
    {
      id: "exp-moon-silent",
      userId: "profile-jun",
      placeId: "place-moon-library",
      caption: "책등 사이에 오래된 여행 메모가 끼어 있었다.",
      tags: ["오래 머물기 좋은 곳", "친구에게 보여주고 싶은 곳"],
      visitedAt: "2026-06-11T08:00:00.000Z",
      showVisitedAt: false,
      visibility: "public",
      status: "active",
      shareToken: "share-exp-moon-silent",
      createdAt: "2026-06-11T12:00:00.000Z",
    },
    {
      id: "exp-rain-yard",
      userId: "profile-minseo",
      placeId: "place-rain-yard",
      caption: "유리 천장에 떨어지는 빗소리가 전시보다 오래 남았다.",
      tags: ["비 오는 날", "카페와 공간"],
      visitedAt: "2026-06-12T08:00:00.000Z",
      showVisitedAt: true,
      visibility: "public",
      status: "active",
      shareToken: "share-exp-rain-yard",
      createdAt: "2026-06-12T13:00:00.000Z",
    },
    {
      id: "exp-archive-quiet",
      userId: DEMO_USER_ID,
      placeId: "place-archive-93",
      caption: "작은 방 하나가 오후 내내 조용한 대답처럼 있었다.",
      tags: ["사라지기 전에 남기고 싶은 곳", "전시"],
      visitedAt: "2026-06-13T06:00:00.000Z",
      showVisitedAt: true,
      visibility: "private",
      status: "active",
      shareToken: "share-exp-archive-quiet",
      createdAt: "2026-06-13T10:00:00.000Z",
    },
  ],
  userPlaces: [
    {
      id: "user-place-brewers",
      userId: DEMO_USER_ID,
      placeId: "place-brewers",
      sourceExperienceId: "exp-brewers-rain",
      savedAt: "2026-06-13T11:00:00.000Z",
    },
    {
      id: "user-place-moon",
      userId: DEMO_USER_ID,
      placeId: "place-moon-library",
      sourceExperienceId: "exp-moon-silent",
      savedAt: "2026-06-13T11:10:00.000Z",
    },
    {
      id: "user-place-rain",
      userId: DEMO_USER_ID,
      placeId: "place-rain-yard",
      sourceExperienceId: "exp-rain-yard",
      savedAt: "2026-06-13T11:20:00.000Z",
    },
  ],
  tasteMaps: [
    {
      id: "map-rainy-cafes",
      ownerId: "profile-minseo",
      title: "비 오는 날 오래 앉기",
      story: "창밖 소리와 커피 향이 같이 느려지는 장소들.",
      coverType: "collage",
      coverTone: "mint",
      visibility: "public",
      status: "published",
      shareToken: "share-map-rainy-cafes",
      createdAt: "2026-06-15T09:00:00.000Z",
      saveCount: 37,
    },
    {
      id: "map-slow-weekend",
      ownerId: DEMO_ADMIN_ID,
      title: "서두르지 않는 주말",
      story: "서촌에서 남산까지, 대화가 끊겨도 좋은 동선.",
      coverType: "gradient",
      coverTone: "amber",
      visibility: "public",
      status: "published",
      shareToken: "share-map-slow-weekend",
      createdAt: "2026-06-14T09:00:00.000Z",
      saveCount: 64,
    },
    {
      id: "map-yuna-hidden",
      ownerId: DEMO_USER_ID,
      title: "혼자만 알고 싶은 오후",
      story: "잠깐 숨을 고르기 좋은 장소.",
      coverType: "first_media",
      coverTone: "coral",
      visibility: "private",
      status: "published",
      shareToken: "share-map-yuna-hidden",
      createdAt: "2026-06-16T09:00:00.000Z",
      saveCount: 0,
    },
  ],
  tasteMapItems: [
    {
      id: "item-rainy-1",
      tasteMapId: "map-rainy-cafes",
      placeId: "place-brewers",
      sourceExperienceId: "exp-brewers-rain",
      itemNote: "첫 잔은 창가에서.",
      sortOrder: 1,
    },
    {
      id: "item-rainy-2",
      tasteMapId: "map-rainy-cafes",
      placeId: "place-rain-yard",
      sourceExperienceId: "exp-rain-yard",
      itemNote: "비를 들으러 들르는 곳.",
      sortOrder: 2,
    },
    {
      id: "item-slow-1",
      tasteMapId: "map-slow-weekend",
      placeId: "place-moon-library",
      sourceExperienceId: "exp-moon-silent",
      itemNote: null,
      sortOrder: 1,
    },
    {
      id: "item-slow-2",
      tasteMapId: "map-slow-weekend",
      placeId: "place-blue-stairs",
      sourceExperienceId: null,
      itemNote: null,
      sortOrder: 2,
    },
    {
      id: "item-slow-3",
      tasteMapId: "map-slow-weekend",
      placeId: "place-archive-93",
      sourceExperienceId: "exp-archive-quiet",
      itemNote: null,
      sortOrder: 3,
    },
    {
      id: "item-hidden-1",
      tasteMapId: "map-yuna-hidden",
      placeId: "place-brewers",
      sourceExperienceId: "exp-brewers-rain",
      itemNote: null,
      sortOrder: 1,
    },
  ],
  tasteMapSaves: [
    {
      userId: DEMO_USER_ID,
      tasteMapId: "map-rainy-cafes",
      savedAt: "2026-06-16T10:00:00.000Z",
    },
  ],
  reports: [
    {
      id: "report-exp-rain",
      reporterId: DEMO_USER_ID,
      targetType: "experience",
      targetId: "exp-rain-yard",
      reason: "장소 정보 확인 요청",
      detail: "주소가 근처 다른 공간과 헷갈릴 수 있어 보입니다.",
      status: "pending",
      createdAt: "2026-06-18T08:00:00.000Z",
    },
  ],
  featuredContent: [
    {
      id: "featured-week",
      contentType: "taste_map",
      contentId: "map-rainy-cafes",
      section: "weekly",
      sortOrder: 1,
      active: true,
    },
    {
      id: "featured-curator",
      contentType: "taste_map",
      contentId: "map-slow-weekend",
      section: "curator",
      sortOrder: 1,
      active: true,
    },
  ],
  recentViews: [
    {
      userId: DEMO_USER_ID,
      contentType: "place",
      contentId: "place-brewers",
      viewedAt: "2026-06-20T08:00:00.000Z",
    },
    {
      userId: DEMO_USER_ID,
      contentType: "taste_map",
      contentId: "map-rainy-cafes",
      viewedAt: "2026-06-20T08:20:00.000Z",
    },
  ],
}
